[package]
name = "dxc-macros"
description = "The Macros of Dxc Crate"
keywords = ["dxc", "macros", "dxc-macros"]
edition = "2024"
rust-version = "1.89.0"
version = "0.2.0"
authors = ["efahnjoe"]
license = "MIT"
repository = "https://github.com/efahnjoe/dxc-macros"
homepage = "https://github.com/efahnjoe/dxc-macros#README.md"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
darling = "^0.23.0"
dioxus = { version = "^0.7.3", features = ["fullstack"] }
proc-macro2 = "^1.0.97"
quote = "^1.0.40"
syn = { version = "^2.0.105", features = ["full", "parsing"] }
